#ifndef DEFS_H
#define DEFS_H

#include "driver/ledc.h"

#define ENCODER_MAX_LIMIT (1<<12)
#define ENCODER_LOW_LIMIT -(1<<12)

#define ENCODER_CHN_A_GPIO 5
#define ENCODER_CHN_B_GPIO -1

#define MOTOR_DC_M1_GPIO 21
#define MOTOR_DC_M1_CHANNEL LEDC_CHANNEL_0

#define MOTOR_DC_M2_GPIO 22
#define MOTOR_DC_M2_CHANNEL LEDC_CHANNEL_1

#define MOTOR_DC_PWM_TIMER LEDC_TIMER_0
#define MOTOR_DC_SPEED LEDC_HIGH_SPEED_MODE
#define MOTOR_DC_CLOCK_SOURCE LEDC_AUTO_CLK
#define MOTOR_DC_FREQ 4000
#define MOTOR_DC_RESOLUTION_PWM LEDC_TIMER_10_BIT

#define TIMER_RESOLUTION_HZ 1000000

#define FREQUENCIA_HZ_AMOSTRAGEM_ENCODER 50000

#endif